;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        c-up-conditional
        end-of-visual-line
        kill-visual-line
        smarter-move-beginning-of-line
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
